# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/sda2/Development/C++/RVPT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/sda2/Development/C++/RVPT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/legend/Applications/clion-2019.3.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sda2/Development/C++/RVPT/CMakeFiles /mnt/sda2/Development/C++/RVPT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/sda2/Development/C++/RVPT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rvpt

# Build rule for target.
rvpt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rvpt
.PHONY : rvpt

# fast build rule for target.
rvpt/fast:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/build
.PHONY : rvpt/fast

#=============================================================================
# Target rules for targets named compile-shaders

# Build rule for target.
compile-shaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compile-shaders
.PHONY : compile-shaders

# fast build rule for target.
compile-shaders/fast:
	$(MAKE) -f CMakeFiles/compile-shaders.dir/build.make CMakeFiles/compile-shaders.dir/build
.PHONY : compile-shaders/fast

#=============================================================================
# Target rules for targets named copy-asset-files

# Build rule for target.
copy-asset-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 copy-asset-files
.PHONY : copy-asset-files

# fast build rule for target.
copy-asset-files/fast:
	$(MAKE) -f CMakeFiles/copy-asset-files.dir/build.make CMakeFiles/copy-asset-files.dir/build
.PHONY : copy-asset-files/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named vk-bootstrap

# Build rule for target.
vk-bootstrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vk-bootstrap
.PHONY : vk-bootstrap

# fast build rule for target.
vk-bootstrap/fast:
	$(MAKE) -f external/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build.make external/vk-bootstrap/CMakeFiles/vk-bootstrap.dir/build
.PHONY : vk-bootstrap/fast

#=============================================================================
# Target rules for targets named glm_dummy

# Build rule for target.
glm_dummy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glm_dummy
.PHONY : glm_dummy

# fast build rule for target.
glm_dummy/fast:
	$(MAKE) -f external/glm/glm/CMakeFiles/glm_dummy.dir/build.make external/glm/glm/CMakeFiles/glm_dummy.dir/build
.PHONY : glm_dummy/fast

src/rvpt/main.o: src/rvpt/main.cpp.o

.PHONY : src/rvpt/main.o

# target to build an object file
src/rvpt/main.cpp.o:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/main.cpp.o
.PHONY : src/rvpt/main.cpp.o

src/rvpt/main.i: src/rvpt/main.cpp.i

.PHONY : src/rvpt/main.i

# target to preprocess a source file
src/rvpt/main.cpp.i:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/main.cpp.i
.PHONY : src/rvpt/main.cpp.i

src/rvpt/main.s: src/rvpt/main.cpp.s

.PHONY : src/rvpt/main.s

# target to generate assembly for a file
src/rvpt/main.cpp.s:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/main.cpp.s
.PHONY : src/rvpt/main.cpp.s

src/rvpt/rvpt.o: src/rvpt/rvpt.cpp.o

.PHONY : src/rvpt/rvpt.o

# target to build an object file
src/rvpt/rvpt.cpp.o:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/rvpt.cpp.o
.PHONY : src/rvpt/rvpt.cpp.o

src/rvpt/rvpt.i: src/rvpt/rvpt.cpp.i

.PHONY : src/rvpt/rvpt.i

# target to preprocess a source file
src/rvpt/rvpt.cpp.i:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/rvpt.cpp.i
.PHONY : src/rvpt/rvpt.cpp.i

src/rvpt/rvpt.s: src/rvpt/rvpt.cpp.s

.PHONY : src/rvpt/rvpt.s

# target to generate assembly for a file
src/rvpt/rvpt.cpp.s:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/rvpt.cpp.s
.PHONY : src/rvpt/rvpt.cpp.s

src/rvpt/vk_util.o: src/rvpt/vk_util.cpp.o

.PHONY : src/rvpt/vk_util.o

# target to build an object file
src/rvpt/vk_util.cpp.o:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/vk_util.cpp.o
.PHONY : src/rvpt/vk_util.cpp.o

src/rvpt/vk_util.i: src/rvpt/vk_util.cpp.i

.PHONY : src/rvpt/vk_util.i

# target to preprocess a source file
src/rvpt/vk_util.cpp.i:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/vk_util.cpp.i
.PHONY : src/rvpt/vk_util.cpp.i

src/rvpt/vk_util.s: src/rvpt/vk_util.cpp.s

.PHONY : src/rvpt/vk_util.s

# target to generate assembly for a file
src/rvpt/vk_util.cpp.s:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/vk_util.cpp.s
.PHONY : src/rvpt/vk_util.cpp.s

src/rvpt/window.o: src/rvpt/window.cpp.o

.PHONY : src/rvpt/window.o

# target to build an object file
src/rvpt/window.cpp.o:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/window.cpp.o
.PHONY : src/rvpt/window.cpp.o

src/rvpt/window.i: src/rvpt/window.cpp.i

.PHONY : src/rvpt/window.i

# target to preprocess a source file
src/rvpt/window.cpp.i:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/window.cpp.i
.PHONY : src/rvpt/window.cpp.i

src/rvpt/window.s: src/rvpt/window.cpp.s

.PHONY : src/rvpt/window.s

# target to generate assembly for a file
src/rvpt/window.cpp.s:
	$(MAKE) -f CMakeFiles/rvpt.dir/build.make CMakeFiles/rvpt.dir/src/rvpt/window.cpp.s
.PHONY : src/rvpt/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... rvpt"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... compile-shaders"
	@echo "... copy-asset-files"
	@echo "... edit_cache"
	@echo "... glfw"
	@echo "... vk-bootstrap"
	@echo "... glm_dummy"
	@echo "... src/rvpt/main.o"
	@echo "... src/rvpt/main.i"
	@echo "... src/rvpt/main.s"
	@echo "... src/rvpt/rvpt.o"
	@echo "... src/rvpt/rvpt.i"
	@echo "... src/rvpt/rvpt.s"
	@echo "... src/rvpt/vk_util.o"
	@echo "... src/rvpt/vk_util.i"
	@echo "... src/rvpt/vk_util.s"
	@echo "... src/rvpt/window.o"
	@echo "... src/rvpt/window.i"
	@echo "... src/rvpt/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

