name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        config: [Debug, Release]
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    container:
      image: nickclark2016/vulkan-sdk-containers:${{ matrix.os }}-1.2.135

    steps:
      - uses: actions/checkout@v2
      - name: cmake-install
        run: |
          apt update && \
          apt-get install -y curl && \
          curl -sL https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.sh -o cmakeinstall.sh && \
          chmod +x cmakeinstall.sh && \
          ./cmakeinstall.sh --prefix=/usr/local --exclude-subdir && \
          rm cmakeinstall.sh
      - name: build
        run: mkdir build && cd build && rm -rf * && cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} .. && cmake --build .
